from ..abstract.retorno import TIPO_DATO

TablaSuma = [
    #bit                #int                    #decimal            #date            #datetime      #nchar                  #nvarchar
    [TIPO_DATO.BIT,      TIPO_DATO.INT,       TIPO_DATO.DECIMAL,   TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NULL,          TIPO_DATO.NULL],
    [TIPO_DATO.INT,      TIPO_DATO.INT,       TIPO_DATO.DECIMAL,   TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NULL,          TIPO_DATO.NULL],
    [TIPO_DATO.DECIMAL,  TIPO_DATO.DECIMAL,   TIPO_DATO.DECIMAL,   TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NULL,          TIPO_DATO.NULL],
    [TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NULL,          TIPO_DATO.NULL],
    [TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NULL,          TIPO_DATO.NULL],
    [TIPO_DATO.NCHAR,    TIPO_DATO.NCHAR,     TIPO_DATO.NCHAR,     TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NCHAR,         TIPO_DATO.NVARCHAR],
    [TIPO_DATO.NVARCHAR, TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR,  TIPO_DATO.NULL, TIPO_DATO.NULL, TIPO_DATO.NVARCHAR,      TIPO_DATO.NVARCHAR]
]

TablaResta = [
    #bit                #int                #decimal
    [TIPO_DATO.NULL,    TIPO_DATO.INT,      TIPO_DATO.DECIMAL],
    [TIPO_DATO.INT,     TIPO_DATO.INT,      TIPO_DATO.DECIMAL],
    [TIPO_DATO.DECIMAL, TIPO_DATO.DECIMAL,  TIPO_DATO.DECIMAL]
]

TablaMultiplicacion = [
    #bit                #int                #decimal            #date           #datetime       #nchar          #nvarchar
    [TIPO_DATO.BIT,     TIPO_DATO.INT,      TIPO_DATO.DECIMAL,  TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.INT,     TIPO_DATO.INT,      TIPO_DATO.DECIMAL,  TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.DECIMAL, TIPO_DATO.DECIMAL,  TIPO_DATO.DECIMAL,  TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.NULL,    TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR],
    [TIPO_DATO.NULL,    TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR],
    [TIPO_DATO.NULL,    TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR,  TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.NULL,    TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR,  TIPO_DATO.NULL,      TIPO_DATO.NULL]
]

TablaDivision = [
    #bit            #int            #decimal        #date           #datetime       #nchar          #nvarchar
    [TIPO_DATO.NULL,     TIPO_DATO.INT,       TIPO_DATO.DECIMAL,   TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.INT,      TIPO_DATO.INT,       TIPO_DATO.DECIMAL,   TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.DECIMAL,  TIPO_DATO.DECIMAL,   TIPO_DATO.DECIMAL,   TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR],
    [TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR],
    [TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR,  TIPO_DATO.NULL,      TIPO_DATO.NULL],
    [TIPO_DATO.NULL,     TIPO_DATO.NULL,      TIPO_DATO.NULL,      TIPO_DATO.NVARCHAR,  TIPO_DATO.NVARCHAR,  TIPO_DATO.NULL,      TIPO_DATO.NULL]
]

TablaAsignacion = [
    #bit                    #int                   #decimal             #date        #datetime         #nchar                #nvarchar
    [TIPO_DATO.BIT,       TIPO_DATO.BIT,        TIPO_DATO.NULL,     TIPO_DATO.NULL, TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NULL],
    [TIPO_DATO.INT,       TIPO_DATO.INT,        TIPO_DATO.DECIMAL,  TIPO_DATO.NULL, TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NULL],
    [TIPO_DATO.NULL,      TIPO_DATO.DECIMAL,    TIPO_DATO.DECIMAL,  TIPO_DATO.NULL, TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NULL],
    [TIPO_DATO.NULL,      TIPO_DATO.NULL,       TIPO_DATO.NULL,     TIPO_DATO.DATE, TIPO_DATO.NULL,     TIPO_DATO.NULL,     TIPO_DATO.NULL],
    [TIPO_DATO.NULL,      TIPO_DATO.NULL,       TIPO_DATO.NULL,     TIPO_DATO.NULL, TIPO_DATO.DATETIME, TIPO_DATO.NULL,     TIPO_DATO.NULL],
    [TIPO_DATO.NULL,      TIPO_DATO.NULL,       TIPO_DATO.NULL,     TIPO_DATO.NULL, TIPO_DATO.NULL,     TIPO_DATO.NCHAR,    TIPO_DATO.NCHAR],
    [TIPO_DATO.NULL,      TIPO_DATO.NULL,       TIPO_DATO.NULL,     TIPO_DATO.NULL, TIPO_DATO.NULL,     TIPO_DATO.NVARCHAR, TIPO_DATO.NVARCHAR]
]
